### PR TITLE
wip feat/e2e test

### PR DESCRIPTION
**Pull request by mathe42**

### CODE REVIEW

**Comment by mathe42** [comment]
@oberbeck can you have a look? Files in test/e2e/scripts are not ready. But Github action is finished.

**Comment by oberbeck** [comment]
> @oberbeck can you have a look? Files in test/e2e/scripts are not ready. But Github action is finished.

I will, hopefully tonight. I am currently at my day job...

**Review by oberbeck — COMMENTED** [review]
Although I like the setup so far, it kind of bothers me to not have a typescript setup. Nevertheless, I understand this is probably the easiest.

**Comment by mathe42** [comment]
> Although I like the setup so far, it kind of bothers me to not have a typescript setup. Nevertheless, I understand this is probably the easiest.

With this comment:

**Pull request closed without merging**
